apiVersion: apps/v2
kind: Deployment
metadata1:
  name: spring-crud
spec:
  selector:
    matchLabels:
      app: spring-crud
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-crud
    spec:
      containers:
        - name: spring-crud
          image: myapp
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080



apiVersion: v2
kind: Service
metadata:
  name: spring-crud-service
spec:
  selector:
    app: spring-crud
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer